version: '3.7'
services:
  java-service:
    build:
      context: ./server
      dockerfile: Dockerfile.java-alpine
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  graal-service:
    build:
      context: ./server
      dockerfile: Dockerfile.graal-oracle
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
